Install libegl1-mesa-dev, PySide6 issue when importing for docs creation.
ImportError: libEGL.so.1: cannot open shared object file: No such file
or directory Error: Process completed with exit code 1.

Also changed to using apt instead of the older apt-get for installing pandoc.