Change in Python 3.10.11 causes import error.
Change in 3.10.11 requires "import importlib.util". Using "import
importlib" and then referring to the util module no longer works
(AttributeError: module 'importlib' has no attribute 'util').